### ISSUE TITLE
Issues with Noise and Flickering When Using ArchVis Tools with UArchVisMoviePipelineDeferredPass

### ISSUE THREAD

**Issue by ttxian8** [Voulz/ArchVisTools#4]
I am currently using ArchVis Tools to render photos with the movie render queue, but the results using UArchVisMoviePipelineDeferredPass and UMoviePipelineDeferredPassBase are completely different. The photos rendered with UArchVisMoviePipelineDeferredPass are very poor, and it completely fails to render animations. Even a slight camera movement causes full-screen noise. How should I resolve this issue?
![MoviePipelineDeferred_Base](https://github.com/user-attachments/assets/1b3122e4-870e-42ba-8f9e-506e698b1d85)
**### This is rendered using the MoviePipelineDeferred_Base channel.**
![UArchVisMoviePipelineDeferredPass](https://github.com/user-attachments/assets/a6b9e76e-73a5-4b0e-9bf8-783eae1db40f)
**### This is rendered using the ArchVisMoviePipelineDeferredPass channel.**

**Comment by Voulz** [comment]
Sorry to hear you are having issues.
I don't se any particular reason why the output would look that different. The `ArchVisMoviePipelineDeferredPass` is adjusting camera location and perspective matrix, and should therefore have no effect on noise and jagged edges.
This is also the only report of this issue, so I would think this is caused by something else. Could the Anti-aliasing settings/Console variable settings be different in the second render?

Could you firstly confirm:
- which Unreal Engine version you are using
- which version of the plugin you are using
- the same camera and the same settings were used between the 2 renders (apart from the deferred/archvis deferred pass), and if yes, could you send a screenshot of each page of the MRQ settings for both version.

**Comment by ttxian8** [comment]
ue 5.3.2,ArchVis Tools 1.5.5。Both renderings have exactly the same configuration: TSR anti-aliasing, a spatial sampling value of 64, multi-sampling disabled, texture streaming turned off, and no additional configurations. @Voulz

**Comment by ttxian8** [comment]
For anti-aliasing, I used UMoviePipelineDLSSSetting; I misspoke earlier. Both used UMoviePipelineDLSSSetting. You can try it out; I also don’t quite understand the mechanism triggering this issue. @Voulz

**Comment by Voulz** [comment]
@ttxian8, I have tested a simple scene on UE5.3 and I have not been able to reproduce your issue, which suggests this is something related to your setup. I do not have this `UMoviePipelineDLSSSetting` to test with, so there might be a problem with this particular pass. Here are my settings
![image](https://github.com/user-attachments/assets/d948a6b4-e4e9-48fd-b949-ae30c754a9a4)
Deferred Pass:
![NewLevelSequence FinalImage 0010](https://github.com/user-attachments/assets/d9287751-7673-4778-bb2d-48c84e326894)
ArchVis Deferred Pass:
![NewLevelSequence FinalImage ArchVis 0010](https://github.com/user-attachments/assets/4b7cd44c-2336-46e5-8df9-4fa2e04ba9e4)

**Comment by ttxian8** [comment]
It indeed seems to be caused by other settings of mine, but I'm not sure why the rendering results using the `Deferred Pass` and `ArchVis Deferred Pass` channels are different in my current project, despite having exactly the same configurations.

**Comment by Voulz** [comment]
That is a good question, I am not sure why such a difference would happen regardless of the settings.
Have you tried in a more version of the Engine/plugin? you could try to migrate a copy of your project to 5.4 or 5.5 (once the update of the plugin is out) and test it there.

If you find the setting that is responsible for the difference, I could have a look at it. You could also send me a screenshot of each page of your settings (or the .uasset file of your MRQ settings) for me to test on my side, if I see the same issue.

**Comment by ttxian8** [comment]
I'm currently unsure where the problem lies, and as for the settings related to MRQ, I have already mentioned them. I will try changing the version or adjusting other settings to test it out. If there is any news, I will inform you.

**Comment by ttxian8** [comment]
@Voulz I know why the rendering turned out poorly; it was because the ProjectionOffset (Manual Correction) was changed during rendering. However, moving the camera's position does not cause this issue. I think it might be because changing the ProjectionOffset didn't refresh some of the camera's information. Do you have any idea what might be causing this?

**Comment by ttxian8** [comment]
After adjusting the ProjectionOffset, the issue appears from the second frame; parts that move out of the camera's rendering range from the first frame will exhibit the problem. If it completely moves out of the camera's rendering range from the first frame, the entire image of the second frame will have this issue. Thus, I suspect it's because moving the ProjectionOffset does not trigger an update of certain information.
![image](https://github.com/user-attachments/assets/d39c3cd3-9358-407c-b2f1-372a3195b3bc)

**Comment by Voulz** [comment]
Hi, I cannot reproduce this issue on my end.
![image](https://github.com/user-attachments/assets/7084a2db-3579-4974-8818-b8b60975afed)
![image](https://github.com/user-attachments/assets/550869dc-3719-4a64-b417-c8257404bfab)
![image](https://github.com/user-attachments/assets/e81c4aff-cd58-4c17-8bd3-1d5dcc63c80d)
![image](https://github.com/user-attachments/assets/410e7949-e2a3-4870-8a3d-86672b6def62)
If there is an issue with rendering, that would likely be an issue in the engine itself and not something I could fix from a plugin. Try in newer versions of UE, maybe this has been fixed

**Comment by ttxian8** [comment]
Alright, it seems to be an issue with the version of Unreal Engine. Sorry for the trouble.
